#!/bin/sh

#Set postgres password environment variable
export PGPASSWORD=$PG_MASTER_USER_PASSWORD

psql -U $PG_MASTER_USER -h $PG_DB_HOST -w --command "CREATE USER $PG_OKAPI_USER WITH PASSWORD '"$PG_OKAPI_USER_PASSWORD"';"
psql -U $PG_MASTER_USER -h $PG_DB_HOST -w --command "CREATE USER $PG_FOLIO_ADMIN_USER WITH PASSWORD '"$PG_FOLIO_ADMIN_USER_PASSWORD"';"

psql -U $PG_MASTER_USER -h $PG_DB_HOST -w --command "CREATE DATABASE $PG_DATABASE_OKAPI ENCODING 'UTF8' LC_CTYPE 'en_US.UTF-8' LC_COLLATE 'en_US.UTF-8' TEMPLATE 'template0';"
psql -U $PG_MASTER_USER -h $PG_DB_HOST -w --command "CREATE DATABASE $PG_DATABASE_OKAPI_MODULES ENCODING 'UTF8' LC_CTYPE 'en_US.UTF-8' LC_COLLATE 'en_US.UTF-8' TEMPLATE 'template0';"


psql -U $PG_MASTER_USER -h $PG_DB_HOST -w --command "GRANT rds_superuser TO $PG_OKAPI_USER;" &&\
    psql -U $PG_MASTER_USER -h $PG_DB_HOST -w --command "GRANT rds_superuser TO $PG_FOLIO_ADMIN_USER;" &&\
    psql -U $PG_MASTER_USER -h $PG_DB_HOST -w --command "ALTER ROLE $PG_OKAPI_USER CREATEROLE;" &&\
    psql -U $PG_MASTER_USER -h $PG_DB_HOST -w --command "ALTER ROLE $PG_FOLIO_ADMIN_USER CREATEROLE;" &&\
    psql -U $PG_MASTER_USER -h $PG_DB_HOST -w --command "ALTER DATABASE $PG_DATABASE_OKAPI OWNER TO $PG_OKAPI_USER;" &&\
    psql -U $PG_MASTER_USER -h $PG_DB_HOST -w --command "ALTER DATABASE $PG_DATABASE_OKAPI_MODULES OWNER TO $PG_FOLIO_ADMIN_USER;"

