apiVersion: v1
items:
- apiVersion: v1
  kind: Secret
  metadata:
    name: db-connect-okapi
  type: Opaque
  data:
    DB_MAXPOOLSIZE: NTA=
    PG_DATABASE: b2thcGk=
    PG_HOST: cGctb2thcGk=
    PG_PASSWORD: cGFzc3dvcmQ=
    PG_PORT: NTQzMg==
    PG_USERNAME: b2thcGk=
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: hazelcast-rb-q3-2020
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: view
  subjects:
  - kind: ServiceAccount
    name: default
    namespace: folio-q3
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    annotations:
      field.cattle.io/creatorId: "null"
    labels:
      cattle.io/creator: norman
      workload.user.cattle.io/workloadselector: statefulSet-folio-q3-okapi
    name: okapi
  spec:
    podManagementPolicy: OrderedReady
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: statefulSet-folio-q3-okapi
    serviceName: okapi
    template:
      metadata:
        annotations:
          field.cattle.io/ports: '[[{"containerPort":9130,"dnsName":"okapi-nodeport","kind":"NodePort","name":"9130tcp01","protocol":"TCP","sourcePort":0},{"containerPort":5701,"dnsName":"okapi","kind":"ClusterIP","name":"5701tcp02","protocol":"TCP","sourcePort":0},{"containerPort":5702,"dnsName":"okapi","kind":"ClusterIP","name":"5702tcp02","protocol":"TCP","sourcePort":0},{"containerPort":5703,"dnsName":"okapi","kind":"ClusterIP","name":"5703tcp02","protocol":"TCP","sourcePort":0},{"containerPort":5704,"dnsName":"okapi","kind":"ClusterIP","name":"5704tcp02","protocol":"TCP","sourcePort":0},{"containerPort":54327,"dnsName":"okapi","kind":"ClusterIP","name":"54327tcp02","protocol":"TCP","sourcePort":0},{"containerPort":9130,"dnsName":"okapi","kind":"ClusterIP","name":"9130tcp02","protocol":"TCP","sourcePort":0}]]'
        labels:
          workload.user.cattle.io/workloadselector: statefulSet-folio-q3-okapi
      spec:
        containers:
        - env:
          - name: HAZELCAST_IP
            value: $(OKAPI_SERVICE_HOST)
          - name: HAZELCAST_PORT
            value: "5701"
          - name: HAZELCAST_VERTX_PORT
            value: "5702"
          - name: INITDB
            value: "false"
          - name: OKAPI_CLUSTERHOST
            value: $(OKAPI_SERVICE_HOST)
          - name: OKAPI_COMMAND
            value: cluster
          - name: OKAPI_HOST
            value: okapi
          - name: OKAPI_LOGLEVEL
            value: INFO
          - name: OKAPI_PORT
            value: "9130"
          - name: OKAPI_STORAGE
            value: postgres
          - name: OKAPI_URL
            value: http://okapi:9130
          envFrom:
          - secretRef:
              name: db-connect-okapi
              optional: true
          image: <your_registry_IP_FQDN>/<repo>/okapi:q3-2020
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /_/proxy/health
              port: 9130
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 5
          name: okapi
          ports:
          - containerPort: 9130
            name: 9130tcp01
            protocol: TCP
          - containerPort: 5701
            name: 5701tcp02
            protocol: TCP
          - containerPort: 5702
            name: 5702tcp02
            protocol: TCP
          - containerPort: 5703
            name: 5703tcp02
            protocol: TCP
          - containerPort: 5704
            name: 5704tcp02
            protocol: TCP
          - containerPort: 54327
            name: 54327tcp02
            protocol: TCP
          - containerPort: 9130
            name: 9130tcp02
            protocol: TCP
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /_/proxy/health
              port: 9130
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "1"
              memory: 6Gi
            requests:
              cpu: 250m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            procMount: Default
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
        dnsConfig: {}
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: <your_registry_secret>
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    updateStrategy:
      type: RollingUpdate
kind: List
