apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
    field.cattle.io/creatorId: "null"
  labels:
    cattle.io/creator: norman
  managedFields:
  - apiVersion: batch/v1beta1
    manager: rancher
    operation: Update
  - apiVersion: batch/v1beta1
    manager: kube-controller-manager
    operation: Update
  name: ldp-derived-tables
  namespace: folio-prod
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 7
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      activeDeadlineSeconds: 50000
      backoffLimit: 0
      completions: 1
      parallelism: 1
      template:
        metadata:
          annotations:
            field.cattle.io/ports: '[[]]'
          creationTimestamp: null
        spec:
          containers:
          - envFrom:
            - secretRef:
                name: db-config-ldp
                optional: false
            image: harbor.library.tamu.edu/folio/ldp-derived-tables:prod-orchid-v1
            imagePullPolicy: Always
            name: ldp-derived-tables
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {}
              privileged: false
              readOnlyRootFilesystem: false
              runAsNonRoot: false
            stdin: true
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            tty: true
          dnsConfig: {}
          dnsPolicy: ClusterFirst
          imagePullSecrets:
          - name: harbor
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          tolerations:
          - effect: NoSchedule
            key: spring
            operator: Equal
            value: "true"
          - effect: NoSchedule
            key: db
            operator: Equal
            value: "true"
  schedule: 0 9 * * *
  successfulJobsHistoryLimit: 7
  suspend: false
