apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
    field.cattle.io/creatorId: "null"
  labels:
    cattle.io/creator: norman
  managedFields:
  - apiVersion: batch/v1beta1
    manager: rancher
    operation: Update
  - apiVersion: batch/v1beta1
    manager: kube-controller-manager
    operation: Update
  name: ldp-data-update
  namespace: folio-prod
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 7
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      activeDeadlineSeconds: 40000
      backoffLimit: 0
      completions: 1
      parallelism: 1
      template:
        metadata:
          annotations:
          creationTimestamp: null
        spec:
          containers:
          - args:
            - update
            - -D
            - /var/lib/ldp
            - --direct-extraction-no-ssl
            - --trace
            env:
            - name: DATADIR
              value: /var/lib/ldp
            image: ghcr.io/library-data-platform/ldp:1.9.1
            imagePullPolicy: Always
            name: ldp-data-update
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {}
              privileged: false
              readOnlyRootFilesystem: false
              runAsNonRoot: false
            stdin: true
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            tty: true
            volumeMounts:
            - mountPath: /var/lib/ldp/ldpconf.json
              name: ldp-conf
              subPath: ldpconf.json
            - mountPath: /var/lib/ldp
              name: ldp-data
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          tolerations:
          - effect: NoSchedule
            key: spring
            operator: Equal
            value: "true"
          volumes:
          - name: ldp-conf
            secret:
              defaultMode: 420
              optional: false
              secretName: ldp-conf
          - name: ldp-data
            persistentVolumeClaim:
              claimName: ldp-data
  schedule: 0 23 * * *
  successfulJobsHistoryLimit: 7
  suspend: false
