apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    field.cattle.io/creatorId: "null"
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: statefulSet-folio-prod-ldp-server
  managedFields:
  - apiVersion: apps/v1
    manager: rancher
    operation: Update
  - apiVersion: apps/v1
    manager: kube-controller-manager
    operation: Update
  name: ldp-server
  namespace: folio-prod
spec:
  podManagementPolicy: OrderedReady
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: statefulSet-folio-prod-ldp-server
  serviceName: ldp-server
  template:
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: statefulSet-folio-prod-ldp-server
    spec:
      containers:
      - args:
        - upgrade-database
        - -D
        - /var/lib/ldp
        - --direct-extraction-no-ssl
        - --trace
        env:
        - name: DATADIR
          value: /var/lib/ldp
        image: ghcr.io/library-data-platform/ldp:1.9.1
        imagePullPolicy: Always
        name: ldp-server
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /var/lib/ldp/ldpconf.json
          name: ldp-conf
          subPath: ldpconf.json
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: spring
        operator: Equal
        value: "true"
      volumes:
      - name: ldp-conf
        secret:
          defaultMode: 420
          optional: false
          secretName: ldp-conf
  updateStrategy:
    type: OnDelete
