#!/bin/bash

set -e

psql -U postgres -d postgres  -c "CREATE ROLE ${PG_USERNAME} WITH PASSWORD '${PG_PASSWORD}' LOGIN CREATEDB";
psql -U postgres -d postgres  -c "CREATE DATABASE $PG_DATABASE WITH OWNER $PG_USERNAME";
psql -U postgres -d postgres  -c "CREATE ROLE $FOLIO_DATABASE_ROLE_USER WITH PASSWORD '$FOLIO_PASSWORD' LOGIN SUPERUSER";
psql -U postgres -d postgres  -c "CREATE DATABASE $FOLIO_DATABASE WITH OWNER $FOLIO_DATABASE_ROLE_USER";
